services:

  web:
    build: ./APIservice
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./APIservice/.env
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' http://127.0.0.1:8000/"
      interval: 5s
      timeout: 10s
      retries: 5

  db:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./APIservice/.env
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 10s
      retries: 10